// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEc6gKLjV78jni4qkuUfPi8RhdO0MK1kM',
    appId: '1:307511836987:web:1d1e64f701221ad201b71e',
    messagingSenderId: '307511836987',
    projectId: 'blind-2f745',
    authDomain: 'blind-2f745.firebaseapp.com',
    databaseURL: 'https://blind-2f745-default-rtdb.firebaseio.com',
    storageBucket: 'blind-2f745.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vIn5jJ8cIMQK8pxbSuRr_vfgMQSBmFE',
    appId: '1:307511836987:android:8b074d67e3c6221b01b71e',
    messagingSenderId: '307511836987',
    projectId: 'blind-2f745',
    databaseURL: 'https://blind-2f745-default-rtdb.firebaseio.com',
    storageBucket: 'blind-2f745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4Ry7-RQhba7hQTUFvBSJ71eiz8YzW3I',
    appId: '1:307511836987:ios:15658a79f91aa19001b71e',
    messagingSenderId: '307511836987',
    projectId: 'blind-2f745',
    databaseURL: 'https://blind-2f745-default-rtdb.firebaseio.com',
    storageBucket: 'blind-2f745.firebasestorage.app',
    iosClientId: '307511836987-8rehregk1677ri88rfmmh5482h1d8m90.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr4Ry7-RQhba7hQTUFvBSJ71eiz8YzW3I',
    appId: '1:307511836987:ios:15658a79f91aa19001b71e',
    messagingSenderId: '307511836987',
    projectId: 'blind-2f745',
    databaseURL: 'https://blind-2f745-default-rtdb.firebaseio.com',
    storageBucket: 'blind-2f745.firebasestorage.app',
    iosClientId: '307511836987-8rehregk1677ri88rfmmh5482h1d8m90.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEc6gKLjV78jni4qkuUfPi8RhdO0MK1kM',
    appId: '1:307511836987:web:92a5f6169ca8a85001b71e',
    messagingSenderId: '307511836987',
    projectId: 'blind-2f745',
    authDomain: 'blind-2f745.firebaseapp.com',
    databaseURL: 'https://blind-2f745-default-rtdb.firebaseio.com',
    storageBucket: 'blind-2f745.firebasestorage.app',
  );
}
